---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_prefs: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libdvdcss
  - libevent
  - mcrypt
  - mysql
  - postgresql
  - nmap
  - npm
  - n
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - drush
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - fing
  - firefox
  - google-chrome
  - handbrake
  - slack
  - java
  - kdiff3
  - licecap
  - evernote
  - nvalt
  - sequel-pro
  - skype
  - slack
  - iterm2
  - atom
  - transmit
  - psequel
  - visual-studio-code
  - anaconda
  - google-japanese-ime

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
